### ISSUE TITLE
Make mocking properties easier

### ISSUE THREAD

**Issue by jlevitt** [man-group/mockextras#12]
Right now when mocking properties, you have to do something like this:

https://dzone.com/articles/another-approach-mocking

Would it be possible to fold this into the `mockextras` `when().then()` syntax?

**Comment by burrowsa** [comment]
Hi, thanks for the comment. The article you linked is a little old and since then the `PropertyMock` class has been bundled into the `mock` module. It is now more straight forward to mock properties as this example code shows:

    from math import pi, sqrt
    from mock import PropertyMock, patch
    
    
    class Rectangle(object):
        def __init__(self, width, height):
            self.width = width
            self.height = height
    
        @property
        def area(self):
            return self.width * self.height
    
    
    class Circle(object):
        def __init__(self, radius):
            self.radius = radius
    
        @property
        def area(self):
            return self.radius * self.radius * pi
    
        @area.setter
        def area(self, value):
            self.radius = sqrt(value / pi)
    
    
    def test_patch_rectangle_get_area():
        r = Rectangle(10, 10)
    
        assert r.area == 100
    
        with patch.object(Rectangle, "area", new_callable=PropertyMock, return_value=500) as mock_area:
            assert r.area == 500  # return value from the mock
    
        mock_area.assert_called_once_with()  # and the call was recorded
    
    
    def test_patch_circle_set_area():
        c = Circle(10)
    
        c.area = 81 * pi
        assert c.radius == 9
    
        with patch.object(Circle, "area", new_callable=PropertyMock) as mock_area:
            c.area = 10
    
        assert c.area == 81 * pi  # Area not changed because it was patched
        mock_area.assert_called_once_with(10)  # but the call was recorded

However your point about using properties in `mockextras` still stands. Do you have an example of what you'd like to do? I'd like to see some usecases before we modify the API.

**Comment by burrowsa** [comment]
FWIW the first example above could be written with `mockextras` as follows:

    from mockextras import when
    
    def test_patch_rectangle_get_area_mockextras():
        r = Rectangle(10, 10)
    
        assert r.area == 100
    
        with patch.object(Rectangle, "area", new_callable=PropertyMock) as mock_area:
            when(mock_area).called_with().then(500)
            assert r.area == 500  # return value from the mock
    
        mock_area.assert_called_once_with()  # and the call was recorded

and maybe we want to test what happens if the set raises an exception:

    from mock import ANY
    import pytest
    
    
    def test_patch_circle_set_area_mockextras():
        c = Circle(10)
    
        c.area = 81 * pi
        assert c.radius == 9
    
        with pytest.raises(RuntimeError):
            with patch.object(Circle, "area", new_callable=PropertyMock) as mock_area:
                when(mock_area).called_with(ANY).then(RuntimeError)
                c.area = 10

Is there anything else you'd want to be able to do with `@property` and `mockextras`?

**Comment by jlevitt** [comment]
Hi Andrew, sorry for the delayed response. 

I think the `with patch...` syntax is overly verbose and not readily understandable.

Would it be possible to implement something like this? If you think it's possible and like that syntax, I could take a stab at it.

```
from mockextras import when

def test_mock_rectangle_get_area():
    r = Mock()

    when(r.area).as_property().then(100)

    assert r.area == 100
```

**Comment by burrowsa** [comment]
I agree that dealing with properties and mocks is somewhat complex and the syntax required is non-intuitive but mocking properties only really makes sense in terms of patching objects*. One can not create a ```Mock``` object with an attribute called area which is in turn a ```PropertyMock``` that returns ```100``` instead you must patch the ```area``` property on a real class with a ```PropertyMock``` and as I showed above you can then, if you wish, use ```mockextras``` to define its behavior. If you are trying to create a ```Mock``` that mimics the behavior of another object that happens to have a property you can do so simply by treating the property as an attribute. The example you gave can be easily achieved this way, as follows:

    r = Mock(area=100)
    assert r.area == 100

If this doesn't solve your problem, please can you provide  a concrete example of something you are trying to test which would benefit from the kind of thing you are proposing. Like I said above, I'd be keen that any functionality added was driven by a  concrete use-case.



\* actually we have to patch the class - I covered this topic briefly in my talk at PyGotham last year https://youtu.be/Qru_6rXReDg?t=20m4s although others have probably covered it better.

**Comment by jlevitt** [comment]
> If you are trying to create a Mock that mimics the behavior of another object that happens to have a property you can do so simply by treating the property as an attribute.

That does make sense; I could settle for that. My main concern though is the need to switch to a different syntax because I happen to want to mock a property instead of a method. I would much prefer the fluent syntax of `mockextra` for both cases.

One case that I don't see the above helping with is if you did want the mocked property to throw an exception. I think you'd have to fall back to the `patch` syntax, wouldn't you?

```
when(r.area).as_property().then(RuntimeError)
```

would be much nicer :)

**Comment by burrowsa** [comment]
I'm glad you like the fluent API. Putting mockextras to one side for a moment, I don't think it is possible to make an instance of ```Mock``` which has an attribute/property that raises an exception when accessed or has any other side-effect. If ```Mock``` provided this facility then it could be wrapped by the fluent API in a manner similar to your suggestion but it doesn't so I don't think there is anything we can do. Sorry.
